# Generated by Django 5.2.3 on 2025-06-29 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.node')),
            ],
        ),
    ]
