# Generated by Django 5.2.3 on 2025-06-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Metrics',
            new_name='Metric',
        ),
        migrations.RenameField(
            model_name='metric',
            old_name='metrics',
            new_name='metric',
        ),
    ]
