# Generated by Django 5.2.3 on 2025-06-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_rename_metrics_metric_rename_metrics_metric_metric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='metric',
            new_name='node',
        ),
    ]
